// Morphology presets (docs/V2-ROAD-GRAPH.md §9 P5). A preset is a set of
// growth parameters plus a recipe for the direction field's sources. The
// same growth code produces all of them; only the fields and knobs differ.

const BASE = {
  widths: { arterial: 20, collector: 13, local: 9 },
  spacing: { major: 90, minor: 90 },          // block dimensions along major / minor field axes
  lenScale: { arterial: 1.5, collector: 1, local: 1 },
  branch: { arterial: .85, collector: .85, local: .8 },
  arterialSelfBranch: .12,
  popMin: { collector: .05, local: .12 },
  minAngle: 32 * Math.PI / 180,
  snapRadius: 11,
  extendRadius: 14,
  minLength: 16,
  maxTurn: .45,
  jitter: 0,
  stopProb: { arterial: 0, collector: .02, local: .04 },
  bridgeP: { arterial: 1, collector: .45, local: .06 },
  maxBridgeSpan: 150,
  maxDepth: { arterial: 80, collector: 14, local: 10 },
  delay: { arterial: 1, collector: 3, local: 7 },
  diagonals: 0,
  through: ['arterial', 'collector'],      // classes that continue across a road they cross
  budgetScale: 1,
  parcelScale: 1,
  maxBlockArea: 200 * 200,
  secondaryCenters: 1,
  noiseAmp: 0,
  noiseScale: 1 / 150,
};

export const PATTERNS = {
  manhattan: {
    label: 'MANHATTAN', title: ['Rasterstadt', 'GRID / AVENUES / LONG BLOCKS', 'GRID'],
    spacing: { major: 62, minor: 175 },
    lenScale: { arterial: 1.15, collector: 1, local: 1 },
    branch: { arterial: 1, collector: .98, local: .95 },
    arterialSelfBranch: .2,
    diagonals: 1,
    maxTurn: .25,
    secondaryCenters: 1,
    popMin: { collector: .03, local: .05 },
    budgetScale: 1.1,
    sources: (rng, centers) => [{ type: 'grid', angle: rng.float(-.45, .45), x: 0, z: 0, sigma: Infinity, weight: 1 }],
  },
  paris: {
    label: 'PARIS', title: ['Sternstadt', 'RADIAL / BOULEVARDS / PLACES', 'RADIAL'],
    widths: { arterial: 24, collector: 13, local: 8 },
    spacing: { major: 95, minor: 85 },
    lenScale: { arterial: 1.3, collector: 1, local: .9 },
    arterialSelfBranch: .22,
    maxTurn: .5,
    jitter: .04,
    noiseAmp: .14, noiseScale: 1 / 170,
    secondaryCenters: 2,
    parcelScale: .9,
    sources: (rng, centers) => [
      { type: 'grid', angle: rng.float(0, Math.PI), x: 0, z: 0, sigma: Infinity, weight: .25 },
      ...centers.map((c, i) => ({ type: 'radial', x: c.x, z: c.z, sigma: i === 0 ? 240 : 150, weight: i === 0 ? 1.3 : .9 })),
    ],
  },
  tokyo: {
    label: 'TOKYO', title: ['Wabenstadt', 'ORGANIC / FINE GRAIN / LANES', 'FABRIC'],
    widths: { arterial: 18, collector: 11, local: 6 },
    spacing: { major: 52, minor: 46 },
    lenScale: { arterial: 1.8, collector: 1.1, local: 1 },
    branch: { arterial: .8, collector: .9, local: .85 },
    arterialSelfBranch: .06,
    minAngle: 28 * Math.PI / 180,
    snapRadius: 8, extendRadius: 11, minLength: 12,
    maxTurn: .6,
    jitter: .16,
    noiseAmp: .55, noiseScale: 1 / 130,
    secondaryCenters: 2,
    budgetScale: 1.5,
    parcelScale: .62,
    stopProb: { arterial: 0, collector: .03, local: .08 },
    sources: (rng, centers) => [
      { type: 'grid', angle: rng.float(0, Math.PI), x: 0, z: 0, sigma: Infinity, weight: .5 },
      ...centers.slice(1).map(c => ({ type: 'grid', angle: rng.float(0, Math.PI), x: c.x, z: c.z, sigma: 170, weight: .9 })),
    ],
  },
  medieval: {
    label: 'MEDIEVAL', title: ['Altstadt', 'ORGANIC / WALLED CORE / LANES', 'OLD TOWN'],
    widths: { arterial: 12, collector: 8, local: 5 },
    spacing: { major: 42, minor: 36 },
    lenScale: { arterial: 1.4, collector: 1, local: .9 },
    branch: { arterial: .9, collector: .9, local: .8 },
    arterialSelfBranch: .1,
    minAngle: 25 * Math.PI / 180,
    snapRadius: 7, extendRadius: 10, minLength: 10,
    maxTurn: .7,
    jitter: .3,
    noiseAmp: .8, noiseScale: 1 / 90,
    secondaryCenters: 0,
    budgetScale: 1.4,
    parcelScale: .5,
    popMin: { collector: .12, local: .22 },
    stopProb: { arterial: 0, collector: .05, local: .1 },
    maxBlockArea: 150 * 150,
    sources: (rng, centers) => [
      { type: 'radial', x: centers[0].x, z: centers[0].z, sigma: 260, weight: 1 },
      { type: 'grid', angle: rng.float(0, Math.PI), x: 0, z: 0, sigma: Infinity, weight: .2 },
    ],
  },
  atlanta: {
    label: 'ATLANTA', title: ['Vorortstadt', 'SPRAWL / CUL-DE-SACS / ARTERIALS', 'SPRAWL'],
    widths: { arterial: 24, collector: 14, local: 9 },
    spacing: { major: 130, minor: 110 },
    lenScale: { arterial: 1.6, collector: 1, local: .75 },
    branch: { arterial: .75, collector: .7, local: .6 },
    arterialSelfBranch: .1,
    maxTurn: .3,
    jitter: .14,
    noiseAmp: .4, noiseScale: 1 / 240,
    secondaryCenters: 2,
    diagonals: 1,
    budgetScale: .85,
    parcelScale: 1.9,
    popMin: { collector: .08, local: .16 },
    stopProb: { arterial: 0, collector: .06, local: .3 },
    maxBlockArea: 320 * 320,
    sources: (rng, centers) => [
      { type: 'grid', angle: rng.float(0, Math.PI), x: 0, z: 0, sigma: Infinity, weight: .6 },
      ...centers.map(c => ({ type: 'grid', angle: rng.float(0, Math.PI), x: c.x, z: c.z, sigma: 200, weight: .8 })),
    ],
  },
};

export function resolvePreset(name) {
  const p = PATTERNS[name] || PATTERNS.manhattan;
  return { ...BASE, ...p, name: PATTERNS[name] ? name : 'manhattan' };
}
